<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit162551006b8c33d42cf257302056de4c
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Inacho\\' => 7,
        ),
        'E' => 
        array (
            'EmailValidator\\' => 15,
            'EmailData\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Inacho\\' => 
        array (
            0 => __DIR__ . '/..' . '/inacho/php-credit-card-validator/src',
        ),
        'EmailValidator\\' => 
        array (
            0 => __DIR__ . '/..' . '/nojacko/email-validator/src',
        ),
        'EmailData\\' => 
        array (
            0 => __DIR__ . '/..' . '/nojacko/email-data-disposable/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit162551006b8c33d42cf257302056de4c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit162551006b8c33d42cf257302056de4c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit162551006b8c33d42cf257302056de4c::$classMap;

        }, null, ClassLoader::class);
    }
}
