<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Inacho\\' => array($vendorDir . '/inacho/php-credit-card-validator/src'),
    'EmailValidator\\' => array($vendorDir . '/nojacko/email-validator/src'),
    'EmailData\\' => array($vendorDir . '/nojacko/email-data-disposable/src'),
);
